### ISSUE TITLE
Program crashes when unhooking

### ISSUE THREAD

**Issue by NukoOoOoOoO** [cursey/safetyhook#11]
![image](https://user-images.githubusercontent.com/89713806/218575215-6019d642-a42b-4213-ba53-18306c0f8bbb.png)

Code to reproduce:
```cpp
SafetyHookInline hook;

__declspec(noinline) void SayHello(int times)
{
    std::cout << "Hello #" << times << std::endl;
}

void Hooked_SayHello(int times)
{
    hook->call<void, int>(1337);
}

void SayHelloInfinitely()
{
    int count = 0;
    while (true)
    {
        SayHello(count++);
    }
}

int main()
{
    // Starting a thread for SayHello
    std::thread t(SayHelloInfinitely);
    t.detach();

    {
        auto builder = SafetyHookFactory::acquire();
        hook = builder.create_inline(SayHello, Hooked_SayHello);
    }

    std::this_thread::sleep_for(std::chrono::seconds(1));
    hook.reset();
    std::this_thread::sleep_for(std::chrono::seconds(1));

    return 0;
}
```

Although this can be "fixed" by checking nullptr for ``hook``, it doesn't really live up to the library name

Note: The library used in the code is from [Update README.md](https://github.com/cursey/safetyhook/commit/991bb3e3289b8ea58db4bd70fdfbc8296f161497)

**Comment by cursey** [comment]
I've tried addressing your concerns in #12. It still isn't perfectly safe in my opinion but it is an improvement.

**Comment by NukoOoOoOoO** [comment]
Thank you so much for that! I tried the PR and it partially fixes the issue, because it still crashes on unhooking from time to time. Wouldn't it be better to freeze all the threads while unhooking? I might be missing something but I don't see any thread-freezing related in unhook code

**Comment by angelfor3v3r** [comment]
When you call `unique_ptr.reset` then `~InlineHook` gets called which will freeze threads. I don't know what your use cases for unhooking is but it's generally very unsafe unless you have full control over when the function you're hooking is being called. No hooking library, from what I know, fixes this.

**Comment by cursey** [comment]
> Wouldn't it be better to freeze all the threads while unhooking? I might be missing something but I don't see any thread-freezing related in unhook code while readme says `Stops all other threads when creating or deleting hooks`

It freezes the threads when it acquires a builder from the factory:
https://github.com/cursey/safetyhook/blob/c25ad1ab825799ae96fd98d01c1a53e535082bc8/src/InlineHook.cpp#L287-L292

> it still crashes on unhooking from time to time.

Yeah. I think I can further improve the safety by adding a mutex to `InlineHook` but that would incur a (small) performance penalty when `call`'ing the original function. If I add this, I'll probably make it opt-in by providing a `call_safe` method or something that users can choose to use if unhook safety is important for them.

**Comment by cursey** [comment]
I went ahead and implemented the mutex idea for all the *call methods since safety is a priority for this library I felt I should just keep it as fool-proof as possible.
https://github.com/cursey/safetyhook/pull/12/commits/0c2147baa8f12d4eae0f53c54957e7a8125994f7

**Comment by NukoOoOoOoO** [comment]
Thanks for the clarification 👍. I think mutex addresses the issue and don't experience with crashing when unhooking now
