### ISSUE TITLE
LdrpModuleDatatableLock and other ntdll mechanisms can cause a deadlock after thread freezing

### ISSUE THREAD

**Issue by praydog** [cursey/safetyhook#16]
![assfsagf](https://user-images.githubusercontent.com/2909949/219701292-7a8b8783-2f2c-45e0-86d3-bae879306393.png)

Shortly before this, I freeze the threads with `SafetyhookFactory::acquire()`. In one of the functions I call while threads are frozen, I am calling this function:
```cpp
    std::optional<HMODULE> get_module_within(Address address) {
        HMODULE module = nullptr;
        if (GetModuleHandleEx(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS, address.as<LPCSTR>(), &module)) {
            return module;
        }

        return {};
    }
```

This is the offending mutex in ntdll:
![ntdll](https://user-images.githubusercontent.com/2909949/219703642-bc791c66-c525-4e88-b9b1-f58420e3dc62.png)

For now, I've gotten around this by acquiring in multiple places instead of in one giant code block, to limit the potential that I will run into this issue.

**Comment by cursey** [comment]
Should be fixed with latest changes. Reopen if you continue to experience this issue.
