### ISSUE TITLE
Thread IP/register corruption due to late SuspendThread?

### ISSUE THREAD

**Issue by emoose** [cursey/safetyhook#22]
Hi there, many thanks for the update to use NtGetNextThread - since the change I've been having some strange crashes though, where random threads sometimes had exceptions, and RIP of threads would end up at some odd addresses.

Spent a while trying things out and might have found the cause, looking at ThreadFreezer it seems to now fetch thread context before actually suspending it, which I'd guess could mean the thread might execute some more between the context fetch & the suspend.

Changing this section:
https://github.com/cursey/safetyhook/blob/891956890eca963adbc87d4d8ee915c20054f2d7/src/ThreadFreezer.cpp#L58-L67

to something like the older ThreadFreezer used:
```C
            auto thread_ctx = CONTEXT{};

            thread_ctx.ContextFlags = CONTEXT_FULL;

            if (SuspendThread(thread_handle) == (DWORD)-1 || !GetThreadContext(thread_handle, &thread_ctx)) {
                continue;
            }

            m_frozen_threads.push_back({thread_id, thread_handle, thread_ctx});
```

Seemed to solve all the crashes I was getting at least, strangely was only getting this with the game Cyberpunk 2077, maybe that's doing something odd with it's threads there, not sure though.

**Comment by cursey** [comment]
Thanks for the report. Silly mistake on my part. Apologies.
