### ISSUE TITLE
Is it possible to skip the original instruction in midhook?

### ISSUE THREAD

**Issue by asesidaa** [cursey/safetyhook#38]
Thanks for the great library. Now I am trying to implement a midhook that need to replace the original instruction. The original instruction is something like
```
rcpps xmm0, xmm1
```
and I need to replace it with exact computation so that the result will be consistent on both Intel and AMD. 
Is it possible? Maybe related to #37?

**Comment by asesidaa** [comment]
Thanks for the response. 

The problem I am trying to solve is that for example, 
```
rcpps xmm0, xmm0
```
would compute 1/x for the 4 packed floats. However, this instruction would result in different results on Intel and AMD, so I need to replace it with for example divps which would produce the same result.

The problem is after the instruction, the original values (in XMM0) is already replaced with the results, so they are no longer available. So the most robust way is to replace the original instruction (without executing it).

The plan is to use things like asmjit to generate the required instructions as the hook function.

**Comment by cursey** [comment]
I've created a PR #39 that allows you to change the instruction pointer, effectively letting you bypass the trampoline that would execute the original instruction. I think a lot of care will need to be taken to use this safely, but the option is there now. 

I will also be adding XMM register capture to this PR before merging it into main.

**Comment by cursey** [comment]
I've added XMM capture as well to that PR. Let me know if those changes are enough for you to do what you want.

**Comment by asesidaa** [comment]
Thank you, I think it is working in my test
