### ISSUE TITLE
Multiple definition of type_info

### ISSUE THREAD

**Issue by EthanZoneCoding** [cursey/safetyhook#40]
Since the update 2 days ago, I get multiple definition errors when linking. I'm using CLion and cmake 3.26 with C++ 23. pulling the repo like in the example.

```C:\Program Files\JetBrains\CLion 2023.2.1\bin\mingw\bin/ld.exe: C:/Program Files/JetBrains/CLion 2023.2.1/bin/mingw/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0\libstdc++.a(tinfo.o):(.text$_ZNKSt9type_infoeqERKS_+0x0): multiple definition of `std::type_info::operator==(std::type_info const&) const'; _deps/safetyhook-build/libsafetyhook.a(vmt_hook.cpp.obj):C:/Program Files/JetBrains/CLion 2023.2.1/bin/mingw/lib/gcc/x86_64-w64-mingw32/13.1.0/include/c++/typeinfo:194: first defined here```

After a bit of research, this seems to be an issue with static linking in C++ 23.
https://github.com/skeeto/w64devkit/issues/86
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=110572

**Comment by cursey** [comment]
Maybe I'm not understanding the issue fully as I don't typically use mingw but is this a problem with GCC or something I need to fix in safetyhook because it's wrong? If it's a problem with GCC I don't mind working around the issue by making a change, but only if necessary.

**Comment by EthanZoneCoding** [comment]
I'll look at the code introduced with the new commit to try to narrow down the issue. Thanks

**Comment by EthanZoneCoding** [comment]
I moved to MSVC compiler, and the release works. The new workflow is better, I'm not looking back so I'm closing this for now. Maybe if someone else sees it, they can open it. Thanks, I love this library
