### ISSUE TITLE
Allow to disable original bytes restoration in hook's destructor

### ISSUE THREAD

**Issue by ThirteenAG** [cursey/safetyhook#53]
```c
InlineHook::~InlineHook() {
    destroy();
}
```

For example, if dll function was hooked, and this dll was unloaded, `std::copy(m_original_bytes.begin(), m_original_bytes.end(), m_target);` will crash on app exit(or whenever the destructor is called). Would be good to have an option to avoid that, or check for pointer validity inside `::destroy()`; Also applies to mid hook.

**Comment by cursey** [comment]
Can you try #54 and see if it fixes that behavior?

**Comment by ThirteenAG** [comment]
Works fine now, thanks!
