### ISSUE TITLE
Missing call to SetThreadContext

### ISSUE THREAD

**Issue by ifarbod** [cursey/safetyhook#66]
In `fix_ip`, `SetThreadContext` is not called after fixing the thread's IP.

https://github.com/cursey/safetyhook/blob/3f157c8507621e5c0f0fc5c6df597958fe618ed6/src/os.windows.cpp#L259

**Comment by cursey** [comment]
Don't know how I missed that one. Thanks for the heads up. I have put in a PR could you please verify the issue is fixed. #67
